name: CI

on:
  push:
    branches:
      - crawler
      - har-file
      - swagger
      - brokencrystals
  pull_request:
    branches: [main]

jobs:
  start_and_wait_scan:
    runs-on: ubuntu-18.04
    name: A job to run a Nexploit scan
    steps:
      - uses: actions/checkout@v2
      - run: |
          sudo apt update
          sudo curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          sudo apt-get install nodejs-dev node-gyp libssl1.0-dev
          sudo apt-get install nodejs npm
          sudo npm install -g @neuralegion/nexploit-cli --unsafe-perm=true
      - name: Save environment variables
        run: |
          printf "NEXPLOIT_TOKEN=\nREPEATER=${{ secrets.REPEATER }}\n" > .env
          cat .env
      - name: Docker-Compose
        run: |
          sudo docker-compose --env-file=.env up -d
          sudo docker-compose config
      - run: sleep 30s
      - run: sudo docker-compose logs
      - name: Run a NeuraLegion Scan
        id: start
        # You may pin to the exact commit or the version.
        # uses: NeuraLegion/run-scan@29ebd17b4fd6292ce7a238a59401668953b37fbe
        uses: NeuraLegion/run-scan@release
        with:
          # Api Token. You can generate it in Organization section
          api_token: ${{ secrets.NEXPLOIT_TOKEN }}
          # Array of discovery types. Can be: archive, crawler, oas
          discovery_types: |
            ["crawler"]
          # Crawler URLs
          crawler_urls: |
            ["https://qa.brokencrystals.com"]
          # Scan Name
          name: Example Scan
      - name: Get the output scan url 🔗
        run: |
          printf "Scan was started with ID https://app.neuralegion.com/scans/${{ steps.start.outputs.id }}"
      - name: NeuraLegion Wait for Issues
        # You may pin to the exact commit or the version.
        # uses: NeuraLegion/wait-for@dd647d1032d1faf8b3104d10490e7e97e3a029de
        uses: NeuraLegion/wait-for@release
        with:
          # Api Token. You can generate it in Organization section
          api_token: ${{ secrets.NEXPLOIT_TOKEN }}
          # Scan ID to wait for
          scan: ${{ steps.start.outputs.id }}
          wait_for: any
          # Time in seconds for the action to wait for issues
          timeout: 600
      - name: NeuraLegion Stop Scan
        if: ${{ failure() }}
        # You may pin to the exact commit or the version.
        # uses: NeuraLegion/stop-scan@055d66866ebdccc8035fbb44bdbbb3e4f37e0364
        uses: NeuraLegion/stop-scan@release
        with:
          # Api Token. You can generate it in Organization section
          api_token: ${{ secrets.NEXPLOIT_TOKEN }}
          # Scan ID to wait for
          scan: ${{ steps.start.outputs.id }}
